name: Semgrep Docker Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  semgrep:
    name: Run Semgrep via Docker
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep in Docker
        run: |
          docker run --rm \
            -v "${PWD}:/src" \
            returntocorp/semgrep \
            semgrep scan --config=auto --json > semgrep-report.json

      - name: Upload Semgrep results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json
