name: Semgrep Docker Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  semgrep:
    name: Run Semgrep via Docker
    runs-on: self-hosted

    permissions:
      actions: read
      contents: read
      security-events: write  # nécessaire pour publier les résultats dans l'onglet "Security"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep in Docker
        run: |
          docker run --rm \
            -v "${PWD}:/src" \
            returntocorp/semgrep \
            semgrep scan --config=auto --sarif > semgrep-report.sarif

      - name: Upload Semgrep results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.sarif

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-report.sarif
