name: CodeQL Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 3 * * 1'  # Analyse hebdo tous les lundis à 3h UTC

jobs:
  analyze:
    name: Analyze code with CodeQL
    runs-on: self-hosted

    permissions:
      actions: read
      contents: read
      security-events: write  # nécessaire pour publier les résultats dans l'onglet "Security"

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript'] # adapte à ton ou tes langages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3
